services:
  - type: web
    name: divmanage
    runtime: docker
    region: singapore
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: BROADCAST_CONNECTION
        value: pusher
      - key: FILESYSTEM_DISK
        value: local
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DB_URL
        sync: false
      - key: PUSHER_APP_ID
        sync: false
      - key: PUSHER_APP_KEY
        sync: false
      - key: PUSHER_APP_SECRET
        sync: false
      - key: PUSHER_APP_CLUSTER
        sync: false
